create extension if not exists vector with schema extensions;

create table if not exists public.vector_collections (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  embedding_model text not null default 'text-embedding-3-small',
  vector_dimension integer not null default 1536,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vector_collections_name_check
    check (name ~ '^[a-z][a-z0-9_]{0,62}$'),
  constraint vector_collections_model_check
    check (embedding_model = 'text-embedding-3-small'),
  constraint vector_collections_dimension_check
    check (vector_dimension = 1536),
  constraint vector_collections_owner_name_unique unique (owner_id, name),
  constraint vector_collections_owner_id_unique unique (owner_id, id)
);

create table if not exists public.vector_documents (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  collection_id uuid not null,
  source_split_result_id bigint references public.split_results(id) on delete set null,
  chunk_index integer not null,
  chunk_key text not null,
  content text not null,
  content_hash char(64) not null,
  embedding extensions.vector(1536) not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vector_documents_collection_owner_fk
    foreign key (owner_id, collection_id)
    references public.vector_collections(owner_id, id)
    on delete cascade,
  constraint vector_documents_chunk_index_check check (chunk_index >= 0),
  constraint vector_documents_chunk_key_check check (char_length(chunk_key) between 1 and 240),
  constraint vector_documents_content_check check (char_length(content) between 1 and 250000),
  constraint vector_documents_content_hash_check check (content_hash ~ '^[a-f0-9]{64}$'),
  constraint vector_documents_metadata_check check (jsonb_typeof(metadata) = 'object'),
  constraint vector_documents_collection_chunk_unique unique (collection_id, chunk_key)
);

drop trigger if exists set_vector_collections_updated_at on public.vector_collections;
create trigger set_vector_collections_updated_at
before update on public.vector_collections
for each row execute function public.set_updated_at();

drop trigger if exists set_vector_documents_updated_at on public.vector_documents;
create trigger set_vector_documents_updated_at
before update on public.vector_documents
for each row execute function public.set_updated_at();

create index if not exists vector_collections_owner_updated_idx
  on public.vector_collections (owner_id, updated_at desc);
create index if not exists vector_documents_owner_collection_idx
  on public.vector_documents (owner_id, collection_id, created_at desc);
create index if not exists vector_documents_source_split_idx
  on public.vector_documents (source_split_result_id);
create index if not exists vector_documents_embedding_hnsw_idx
  on public.vector_documents
  using hnsw (embedding extensions.vector_cosine_ops);

alter table public.vector_collections enable row level security;
alter table public.vector_documents enable row level security;

revoke all on table public.vector_collections from anon, authenticated;
revoke all on table public.vector_documents from anon, authenticated;
grant all on table public.vector_collections to service_role;
grant all on table public.vector_documents to service_role;
grant usage, select on sequence public.vector_documents_id_seq to service_role;

create or replace function public.list_vector_collections(p_owner_id uuid)
returns table (
  id uuid,
  name text,
  embedding_model text,
  vector_dimension integer,
  row_count bigint,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    collections.id,
    collections.name,
    collections.embedding_model,
    collections.vector_dimension,
    count(documents.id) as row_count,
    collections.created_at,
    collections.updated_at
  from public.vector_collections as collections
  left join public.vector_documents as documents
    on documents.collection_id = collections.id
   and documents.owner_id = p_owner_id
  where collections.owner_id = p_owner_id
  group by collections.id
  order by collections.updated_at desc;
$$;

create or replace function public.match_vector_documents(
  p_owner_id uuid,
  p_collection_id uuid,
  p_query_embedding extensions.vector(1536),
  p_match_count integer default 5
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> p_query_embedding) as similarity
  from public.vector_documents as documents
  where documents.owner_id = p_owner_id
    and documents.collection_id = p_collection_id
  order by documents.embedding <=> p_query_embedding
  limit least(greatest(coalesce(p_match_count, 5), 1), 20);
$$;

revoke all on function public.list_vector_collections(uuid)
  from public, anon, authenticated;
grant execute on function public.list_vector_collections(uuid)
  to service_role;

revoke all on function public.match_vector_documents(uuid, uuid, extensions.vector, integer)
  from public, anon, authenticated;
grant execute on function public.match_vector_documents(uuid, uuid, extensions.vector, integer)
  to service_role;
