create extension if not exists pgcrypto with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.user_api_keys (
  id bigint generated by default as identity primary key,
  user_email text not null,
  key_name text not null,
  encrypted_key text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_api_keys_user_key_unique unique (user_email, key_name)
);

drop trigger if exists set_user_api_keys_updated_at on public.user_api_keys;
create trigger set_user_api_keys_updated_at
before update on public.user_api_keys
for each row execute function public.set_updated_at();

create table if not exists public.parse_results (
  id bigint generated by default as identity primary key,
  run_id uuid not null default gen_random_uuid(),
  user_email text not null,
  document_hash char(64),
  parser_type text not null,
  engine_id text,
  parser_model text,
  parser_version text,
  run_status text not null default 'succeeded',
  run_config jsonb,
  file_name text not null,
  file_size bigint not null,
  mime_type text not null,
  file_storage_key text,
  text_content text,
  html_content text,
  markdown_content text,
  json_content jsonb,
  normalized_document jsonb,
  raw_response jsonb,
  processing_time integer,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint parse_results_run_id_unique unique (run_id),
  constraint parse_results_run_status_check check (
    run_status in ('queued', 'running', 'succeeded', 'failed')
  )
);

create table if not exists public.split_results (
  id bigint generated by default as identity primary key,
  user_email text not null,
  parse_run_id uuid,
  document_hash char(64),
  splitter_type text not null,
  original_text text not null,
  original_text_preview text generated always as (left(original_text, 100)) stored,
  chunk_size integer,
  chunk_overlap integer,
  separator text,
  separators jsonb,
  encoding_name text,
  language text,
  breakpoint_type text,
  source_metadata jsonb,
  chunks jsonb not null,
  chunk_count integer not null,
  processing_time integer,
  created_at timestamptz not null default now(),
  constraint split_results_parse_run_fk
    foreign key (parse_run_id)
    references public.parse_results(run_id)
    on delete set null
);

create index if not exists user_api_keys_user_email_idx
  on public.user_api_keys (user_email);
create index if not exists parse_results_user_created_idx
  on public.parse_results (user_email, created_at desc);
create index if not exists parse_results_document_hash_idx
  on public.parse_results (document_hash);
create index if not exists parse_results_engine_id_idx
  on public.parse_results (engine_id);
create index if not exists split_results_user_created_idx
  on public.split_results (user_email, created_at desc);
create index if not exists split_results_parse_run_id_idx
  on public.split_results (parse_run_id);

alter table public.user_api_keys enable row level security;
alter table public.parse_results enable row level security;
alter table public.split_results enable row level security;

revoke all on table public.user_api_keys from anon, authenticated;
revoke all on table public.parse_results from anon, authenticated;
revoke all on table public.split_results from anon, authenticated;

grant all on table public.user_api_keys to service_role;
grant all on table public.parse_results to service_role;
grant all on table public.split_results to service_role;
grant usage, select on all sequences in schema public to service_role;
